apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-dapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-dapr
  template:
    metadata:
      labels:
        app: nfs-dapr
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "storage-proxy"
        dapr.io/api-token-secret: "dapr-api-token"
    spec:
      volumes:
        - name: shared
          emptyDir: {}
      containers:
        - name: nfs
          image: itsthenetwork/nfs-server-alpine
          volumeMounts:
            - name: shared
              mountPath: /nfsshare
          ports:
            - containerPort: 2049
              name: nfs
          env:
            - name: SYNC
              value: "true"
            - name: SHARED_DIRECTORY
              value: /nfsshare
          securityContext:
            privileged: true
        - name: watcher
          image: ubuntu:latest
          volumeMounts:
            - name: shared
              mountPath: /mnt/watcher
          command: ["/bin/bash", "-c", "apt-get update; apt-get install inotify-tools curl -y;curl https://gist.githubusercontent.com/bhummerstone/92420db52c499f2e4e7a131240354cc2/raw/5cf5d2ad4128f88107e33dc4a9a5101991cf5e48/watcher-dapr.sh -o watcher-dapr.sh; chmod +x  watcher-dapr.sh; ./watcher-dapr.sh $DAPR_API_TOKEN"]
          env:
            - name: DAPR_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dapr-api-token
                  key: token
---
apiVersion: v1
kind: Service
metadata:
  name: nfs
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 2049
  selector:
    app: nfs-dapr